apiVersion: sourceplane.io/v1
kind: Component

metadata:
  name: web-app-infra

spec:
  type: terraform
  domain: platform
  subscribe:
    environments:
      - staging
      - production
  inputs:
    workspace: prod-infrastructure
    environment: production-only
    autoApprove: "false"
    backend: s3
  labels:
    team: platform
    tier: infrastructure
  dependsOn:
    - component: common-services
      environment: ""
      scope: same-environment
      condition: success