apiVersion: sourceplane.io/v1
kind: Component

metadata:
  name: common-services

spec:
  type: helmCommon
  domain: platform
  subscribe:
    environments:
      - development
      - staging
      - production
  inputs:
    name: common-services
    replicas: 1
    chart: oci://mycompany.azurecr.io/helm/charts/common
    imagePullPolicy: IfNotPresent
  labels:
    team: platform
    tier: backend
  dependsOn: []