name: release-oci

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  oci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: sourceplane/tinx-release-action@v1
        with:
          registry: ghcr.io/sourceplane/lite-ci:v0.2.23
          delegate-goreleaser: true